#!/bin/sh

set -e

case "$1" in
    configure|upgrade                            )
        if [ "$1" = "configure" ]; then
            glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
        fi

    ;;
    failed-upgrade                               ) ;;
    abort-upgrade|abort-deconfigure|abort-remove ) ;;
    *                                            )
        echo "Unsupported option $1" ; exit 1
    ;;
esac
