#!/bin/sh

set -e

case "$1" in
    remove|purge|upgrade    )
        if [ "$1" = "configure" ]; then
            glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
        fi
    ;;
    failed-upgrade  ) ;;
    *               ) echo "Unsupported option $1" >&2 ; exit 1 ;;
esac
