#!/bin/sh

set -e

case "$1" in
  remove)
    if [ -d /run/systemd/system ]; then
      systemctl --system daemon-reload >/dev/null || true
    fi

    if [ -x "/usr/bin/deb-systemd-helper" ]; then
      deb-systemd-helper mask 'sbctl.service' >/dev/null || true
    fi
    ;;

  purge)
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
      deb-systemd-helper purge 'sbctl.service' >/dev/null || true
      deb-systemd-helper unmask 'sbctl.service' >/dev/null || true
    fi
    ;;

  *)
    echo "Unsupported option $1" >&2
    exit 1
    ;;
esac
